### ISSUE TITLE
Please publish new version with already fixed warning to hex.pm

### ISSUE THREAD

**Issue by razuf** [elixir-makeup/makeup_elixir#12]
In my Elixir CI (Github, Elixir 1.10)  
https://github.com/razuf/apa/runs/607948165?check_suite_focus=true#step:9:162

I got the following warning:
```
Generated credo app
warning: Mix.Local.path_for/1 is deprecated. Use Mix.path_for/1 instead
##[error]  mix.exs:68: MakeupElixir.Mixfile.build_docs/1

```
I checked it locally - forked credo -> deps.get -> looked into mix.exs:

`    ex_doc = Path.join(Mix.Local.path_for(:escript), "ex_doc")
`

it's still the old version! 

Because @josevalim fixed it with 84ee7a05469b513acda524525ffb481c56d8f0b9  
but its published as @version "0.14.0" to hex.pm before that commit. ;-)

So please publish a new version maybe 0.15.0 to hex.pm and everything should be fine.

Thanks and Kind Regards
Ralph

**Comment by josevalim** [comment]
We are going to push it soon, thanks!
